protein-complex-markers: ../extdata/Protein_list.txt
	R -f protein-complex-markers.R

kristensen2012: ../extdata/22863883_Rep1.txt.gz ../extdata/22863883_Rep2.txt.gz ../extdata/22863883_Rep3.txt.gz
	R -f kristensen2012.R

fabre2015: ../extdata/25561571_Rep1.txt.gz  ../extdata/25561571_Rep2.txt.gz
	R -f fabre2015.R

havugimana2012: ../extdata/22939629.txt.gz
	R -f havugimana2012.R

kirkwood2013: ../extdata/24043423.txt.gz
	R -f kirkwood2013.R

.PHONY: kristensen2012 fabre2015 havugimana2012 kirkwood2013 protein-complex-markers 

